name: Ansible Lint  # feel free to pick your own name

on:
  push:
    branches: [ "*" ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ "*" ]
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@main
